name: Deploy Frontend to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Setup Pages Configuration
        uses: actions/configure-pages@v5
        
      - name: Upload Frontend Folder Assets
        uses: actions/upload-pages-artifact@v3
        with:
          # This tells GitHub to only grab your Frontend web folder files
          path: './Frontend'
          
      - name: Deploy Live to GitHub Cloud
        id: deployment
        uses: actions/deploy-pages@v4